# Generated by Django 3.2.3 on 2021-06-26 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='moneda',
            fields=[
                ('numero', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='pais',
            fields=[
                ('numero', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('numero', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('imagen', models.ImageField(upload_to='', verbose_name='foto')),
                ('p_nombre', models.CharField(max_length=50, verbose_name='p_nombre')),
                ('s_nombre', models.CharField(max_length=50, verbose_name='s_nombre')),
                ('ap_paterno', models.CharField(max_length=50, verbose_name='ap_paterno')),
                ('ap_materno', models.CharField(max_length=50, verbose_name='ap_materno')),
                ('telefono', models.IntegerField(verbose_name='telefono')),
                ('direccion', models.CharField(max_length=400, verbose_name='direccion')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
                ('cantrasenna', models.CharField(max_length=100, verbose_name='contrasenna')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.moneda')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pais')),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('numero', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('imagen', models.ImageField(upload_to='', verbose_name='imagen')),
                ('descripcion', models.CharField(max_length=500, verbose_name='descripcion')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
            ],
        ),
    ]
