# Generated by Django 3.2.3 on 2021-07-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='numero',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
